'use client'

import { Canvas, useFrame } from '@react-three/fiber'
import { Environment, Float, PerspectiveCamera, RoundedBox, Sparkles } from '@react-three/drei'
import { useEffect, useRef, useState } from 'react'
import * as THREE from 'three'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import Lenis from 'lenis'
import { products, type Product } from '../data/products'

gsap.registerPlugin(ScrollTrigger)
const A = '/Delfioredell/assets/'

type Progress = { value:number }
type Pointer = { x:number; y:number }

function Cheese({ product, index, progress, pointer, onSelect }: { product:Product; index:number; progress:React.MutableRefObject<Progress>; pointer:React.MutableRefObject<Pointer>; onSelect:(p:Product)=>void }) {
 const ref=useRef<THREE.Group>(null); const classic=product.id==='classic'; const black=product.id==='black'
 useFrame((_,delta)=>{ if(!ref.current)return; const p=progress.current.value; const spread=index-2; const focus=classic?THREE.MathUtils.clamp((p-.12)/.18,0,1):0; const detail=THREE.MathUtils.clamp((p-.48)/.1,0,1); const x=spread*1.15; ref.current.position.x=THREE.MathUtils.damp(ref.current.position.x,THREE.MathUtils.lerp(x,0,focus)+pointer.current.x*(classic?.025:.07)+ (black?detail*.15:0),5,delta); ref.current.position.y=THREE.MathUtils.damp(ref.current.position.y,(index%2?.2:-.1)+(black?(p*.27):0),5,delta); ref.current.position.z=THREE.MathUtils.damp(ref.current.position.z,-Math.abs(spread)*.43+focus*.6+detail*.8,5,delta); ref.current.rotation.y=THREE.MathUtils.damp(ref.current.rotation.y,pointer.current.x*.04+focus*.15+detail*.18,4,delta); const scale=(classic?1:.82)+focus*(classic?.22:0)+detail*(black?.36:0); ref.current.scale.setScalar(scale) })
 return <group ref={ref} onClick={(e)=>{e.stopPropagation();onSelect(product)}}><RoundedBox args={[1.55,.42,1.55]} radius={.18} smoothness={5}><meshStandardMaterial color={product.color} roughness={product.id==='black'?.58:.78}/></RoundedBox><mesh position={[0,.23,0]} rotation={[-Math.PI/2,0,0]}><circleGeometry args={[.52,48]}/><meshStandardMaterial color="#d9be8b" roughness={.92}/></mesh><mesh position={[0,.245,.01]} rotation={[-Math.PI/2,0,0]}><circleGeometry args={[.18,40]}/><meshBasicMaterial color="#f1e8d6"/></mesh><mesh position={[0,.25,.02]} rotation={[-Math.PI/2,0,0]}><circleGeometry args={[.12,40]}/><meshBasicMaterial color="#294034"/></mesh></group>
}

function Scene({ progress, pointer, onSelect }:{progress:React.MutableRefObject<Progress>;pointer:React.MutableRefObject<Pointer>;onSelect:(p:Product)=>void}) { return <><ambientLight intensity={1.3} color="#ead7b5"/><directionalLight position={[3,5,5]} intensity={3.6} color="#ffe9bd" castShadow/><pointLight position={[-4,1,2]} intensity={4} color="#a97835"/><Environment preset="warehouse" blur={.85}/><mesh position={[0,-.45,0]} rotation={[-Math.PI/2,0,0]}><cylinderGeometry args={[3.2,3.4,.24,64]}/><meshStandardMaterial color="#322b22" roughness={.93}/></mesh>{products.map((p,i)=><Cheese key={p.id} product={p} index={i} progress={progress} pointer={pointer} onSelect={onSelect}/>)}<Float speed={.35} rotationIntensity={.08} floatIntensity={.08}><Sparkles count={35} scale={[8,3,5]} size={1.1} speed={.15} color="#c9a568" opacity={.35}/></Float></> }

export default function DelFioreExperience(){ const experience=useRef<HTMLDivElement>(null); const progress=useRef<Progress>({value:0}); const pointer=useRef<Pointer>({x:0,y:0}); const [selected,setSelected]=useState<Product|null>(null)
 useEffect(()=>{const lenis=new Lenis({lerp:.09,smoothWheel:true});let raf=0;const loop=(t:number)=>{lenis.raf(t);raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);const move=(e:MouseEvent)=>{pointer.current.x=(e.clientX/innerWidth-.5)*2;pointer.current.y=(e.clientY/innerHeight-.5)*-2};const tl=gsap.timeline({scrollTrigger:{trigger:experience.current,start:'top top',end:'+=700%',scrub:1,pin:true,onUpdate:s=>{progress.current.value=s.progress}}});tl.to(progress.current,{value:1,ease:'none',duration:1});window.addEventListener('mousemove',move);const esc=(e:KeyboardEvent)=>e.key==='Escape'&&setSelected(null);window.addEventListener('keydown',esc);return()=>{cancelAnimationFrame(raf);lenis.destroy();tl.kill();window.removeEventListener('mousemove',move);window.removeEventListener('keydown',esc)}},[])
 return <div ref={experience} className="experience-root"><div className="webgl-layer"><Canvas dpr={[1,1.35]} shadows gl={{antialias:true,powerPreference:'high-performance'}}><PerspectiveCamera makeDefault position={[0,.1,6]} fov={38}/><Scene progress={progress} pointer={pointer} onSelect={setSelected}/></Canvas></div><div className="experience-ui"><section className="ui-panel hero-ui"><p className="kicker">VIAZUL MMC / DEL FIORE</p><h1>Artizan pendir,<br/><em>ləzzətin hekayəsi.</em></h1><p>Saf süd, yetişmiş dad və Del Fiore kolleksiyasını kəşf et.</p><a href="#collection">Kəşf etməyə başla <b>↗</b></a></section><section className="ui-panel classic-ui"><p className="kicker">03 / CLASSIC CACİOTTA</p><h2>Klassik<br/><em>Caciotta</em></h2><p>Yumşaq, balanslı və kremli.</p></section><section className="ui-panel collection-ui" id="collection"><p className="kicker">04 / COLLECTIONS</p><h2>İmza <em>kolleksiyamız</em></h2><div className="curve-cards">{products.map(p=><button key={p.id} onClick={()=>setSelected(p)}><img src={A+p.image} alt={p.name}/><span>{p.name}</span></button>)}</div></section><section className="ui-panel story-ui" id="story"><p className="kicker">06 / STORY</p><h2>Zamanla hazırlanır.<br/><em>Əl işi ustalıq.</em></h2></section><section className="ui-panel recipes-ui" id="recipes"><p className="kicker">07 / RECIPES</p><h2>Reseptlər — <em>ilham və ləzzət.</em></h2><a href="#locator">Reseptləri kəşf et ↗</a></section><section className="ui-panel locator-ui" id="locator"><p className="kicker">08 / FIND DEL FIORE</p><h2>Del Fiore-u<br/><em>Bakıda tapın.</em></h2><p>Satış nöqtələri təsdiqləndikdən sonra əlavə olunacaq.</p></section></div>{selected&&<div className="product-detail" role="dialog" aria-modal="true"><button onClick={()=>setSelected(null)} aria-label="Bağla">×</button><img src={A+selected.image} alt={selected.name}/><div><p className="kicker">PRODUCT DETAIL</p><h2>{selected.name}</h2><p>Məhsul məlumatları təsdiqləndikdən sonra burada görünəcək.</p></div></div>}</div> }
